<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 260" role="img"
    aria-labelledby="gegenpress-title" xmlns:c2pa="http://c2pa.org/manifest">
    <metadata>
      <c2pa:manifest>
        AAAWgmp1bWIAAAAeanVtZGMycGEAEQAQgAAAqgA4m3EDYzJwYQAAABZcanVtYgAAAEdqdW1kYzJtYQARABCAAACqADibcQN1cm46YzJwYTo3NmIxZmVkNS1kNjIxLTRiMDEtYjgxOS1jODhkNjEzZGYxZDcAAAADl2p1bWIAAAApanVtZGMyYXMAEQAQgAAAqgA4m3EDYzJwYS5hc3NlcnRpb25zAAAAALxqdW1iAAAARGp1bWRjYm9yABEAEIAAAKoAOJtxE2MycGEuaW5ncmVkaWVudC52MwAAAAAYYzJzaOfJW6NwNBo/jtK3j9PV8KYAAABwY2JvcqNpZGM6Zm9ybWF0bWltYWdlL3N2Zyt4bWxqaW5zdGFuY2VJRHgseG1wOmlpZDo1MTExNGI2NC1mMTg3LTQ3MzMtOWM0Mi03ZGNlYWVhZjhlODNscmVsYXRpb25zaGlwaHBhcmVudE9mAAAB4mp1bWIAAABBanVtZGNib3IAEQAQgAAAqgA4m3ETYzJwYS5hY3Rpb25zLnYyAAAAABhjMnNoR2wfgevq/z6ML+oeNvXaZwAAAZljYm9yomdhY3Rpb25zgqJmYWN0aW9ua2MycGEub3BlbmVkanBhcmFtZXRlcnOha2luZ3JlZGllbnRzgaJjdXJseC1zZWxmI2p1bWJmPWMycGEuYXNzZXJ0aW9ucy9jMnBhLmluZ3JlZGllbnQudjNkaGFzaFggIxno6zeLuwm1H5jz1gKdK8o5pbh6jzcFyVzBZvGUVv+kZmFjdGlvbngdY29tLmFudGhyb3BpYy5jbGF1ZGUucHJvdmlkZWRqcGFyYW1ldGVyc6F4H2NvbS5hbnRocm9waWMub3JpZ2luLWNvbmZpZGVuY2VndW5rbm93bmtkZXNjcmlwdGlvbnhmQ2xhdWRlIHByb3ZpZGVkIHRoaXMgZmlsZSBhdCB0aGUgcmVxdWVzdCBvZiBhIHVzZXIgYW5kIG1heSBoYXZlIGNyZWF0ZWQgb3IgbW9kaWZpZWQgdGhlIGZpbGUgY29udGVudHMubXNvZnR3YXJlQWdlbnShZG5hbWVmQ2xhdWRlcmFsbEFjdGlvbnNJbmNsdWRlZPUAAADIanVtYgAAAEBqdW1kY2JvcgARABCAAACqADibcRNjMnBhLmhhc2guZGF0YQAAAAAYYzJzaGXzQhfUO0pjdQL3poNsgcgAAACAY2JvcqVjYWxnZnNoYTI1NmNwYWRNAAAAAAAAAAAAAAAAAGRoYXNoWCD9VbLLUd2U5T/VCak9zZVv03l3K/xTL/B6pSWium31lmRuYW1lbmp1bWJmIG1hbmlmZXN0amV4Y2x1c2lvbnOBomVzdGFydBjEZmxlbmd0aBkeBAAAAj5qdW1iAAAAJ2p1bWRjMmNsABEAEIAAAKoAOJtxA2MycGEuY2xhaW0udjIAAAACD2Nib3KlY2FsZ2ZzaGEyNTZpc2lnbmF0dXJleE1zZWxmI2p1bWJmPS9jMnBhL3VybjpjMnBhOjc2YjFmZWQ1LWQ2MjEtNGIwMS1iODE5LWM4OGQ2MTNkZjFkNy9jMnBhLnNpZ25hdHVyZWppbnN0YW5jZUlEeCx4bXA6aWlkOjBmZTk1ZThjLTdmMDEtNDJmNC1iNzFmLTFmYjFjNjdhYTNkZXJjcmVhdGVkX2Fzc2VydGlvbnODomN1cmx4LXNlbGYjanVtYmY9YzJwYS5hc3NlcnRpb25zL2MycGEuaW5ncmVkaWVudC52M2RoYXNoWCAjGejrN4u7CbUfmPPWAp0ryjmluHqPNwXJXMFm8ZRW/6JjdXJseCpzZWxmI2p1bWJmPWMycGEuYXNzZXJ0aW9ucy9jMnBhLmFjdGlvbnMudjJkaGFzaFggIZbI56pkoKkpl12l5vm+3lWbM297NORoyzdcAfe5iraiY3VybHgpc2VsZiNqdW1iZj1jMnBhLmFzc2VydGlvbnMvYzJwYS5oYXNoLmRhdGFkaGFzaFgg2bbxikzS3lrUSkpKHhMYdt9tT/dL1j5odVrA2Y/SBRl0Y2xhaW1fZ2VuZXJhdG9yX2luZm+jZG5hbWVvQW50aHJvcGljIEZpbGVzZ3ZlcnNpb25lMS4wLjBrc3BlY1ZlcnNpb25lMi40LjAAABA4anVtYgAAAChqdW1kYzJjcwARABCAAACqADibcQNjMnBhLnNpZ25hdHVyZQAAABAIY2JvctKEWQISogEmGCFZAgowggIGMIIBjaADAgECAhRA5aAK7sI50L64g/oGQgU9Z1UTADAKBggqhkjOPQQDAzBJMRcwFQYDVQQKEw5BbnRocm9waWMsIFBCQzEuMCwGA1UEAxMlQW50aHJvcGljIENvbnRlbnQgQ3JlZGVudGlhbHMgUm9vdCBDQTAeFw0yNjA4MDcxODQzNTZaFw0yODA4MDYxOTQzNTZaMEQxFzAVBgNVBAoTDkFudGhyb3BpYywgUEJDMSkwJwYDVQQDEyBBbnRocm9waWMgQ2xhdWRlIENvbnRlbnQgU2lnbmluZzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJh6CmvLUBgFFNU0vUKlOVtE6djd17L5SuwX0LemFisBM3dkd/3cyjxFA3Qo5S46fX0/ihY0VZ7mfb9KF703t5OjWDBWMA4GA1UdDwEB/wQEAwIHgDAVBgNVHSUEDjAMBgorBgEEAYPoXgIBMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUzlHiBIFOZFsj+OPEz5o+nMHXXMIwCgYIKoZIzj0EAwMDZwAwZAIwMXMdFJ4BetLLVY7ORuE9noqbbAZOZn/aArXyTwFAZfKrPzxF2vPoJNf1+UCdg1XGAjBwX1zd9WGqYkqmL5SFqw1QySjr1zJfpJM9+1rdDwSPLMOPOjKuiXjoU/pUUeG9RwmhY3BhZFkNngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPZYQG25zfIBuVGBRTsU5UDFoc3rtMH4o1OHJHJ5v2WQw94mPw1XDlnOSJ9XwfM+7gHa1T8rftJtEkDEY+74X2r9+68=
      </c2pa:manifest>
    </metadata>
    <title id="gegenpress-title">Gegenpress / High-Press</title>
    <defs>
      <marker id="gegenpress-arrow-cyan" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5"
        orient="auto-start-reverse">
        <path d="M0 0 L10 5 L0 10 Z" fill="#00e8ff" />
      </marker>
      <marker id="gegenpress-arrow-run" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5"
        orient="auto-start-reverse">
        <path d="M0 0 L10 5 L0 10 Z" fill="#7a8494" />
      </marker>
    </defs>
    <rect x="10" y="10" width="380" height="240" fill="#0e1218" />
    <g fill="none" stroke="#2c3542" stroke-width="2">
      <rect x="10" y="10" width="380" height="240" />
      <line x1="200" y1="10" x2="200" y2="250" />
      <circle cx="200" cy="130" r="33" />
      <rect x="10" y="59" width="60" height="142" />
      <rect x="10" y="97" width="20" height="66" />
      <rect x="330" y="59" width="60" height="142" />
      <rect x="370" y="97" width="20" height="66" />
      <path d="M70 108 A 33 33 0 0 1 70 152" />
      <path d="M330 108 A 33 33 0 0 0 330 152" />
    </g>
    <g fill="#2c3542">
      <circle cx="200" cy="130" r="2.5" />
      <circle cx="48" cy="130" r="2.5" />
      <circle cx="352" cy="130" r="2.5" />
    </g>
    <line x1="168" y1="14" x2="168" y2="246" stroke="#7a8494" stroke-width="1.5" stroke-dasharray="2 5" />
    <rect class="gegenpress-zone" x="246" y="86" width="78" height="78" fill="#00e8ff" fill-opacity="0.07"
      stroke="#00e8ff" stroke-width="1.5" stroke-dasharray="5 4" />
    <rect x="280" y="120" width="10" height="10" fill="none" stroke="#4a5566" stroke-width="2" />
    <rect x="340" y="65" width="10" height="10" fill="none" stroke="#4a5566" stroke-width="2" />
    <rect x="345" y="190" width="10" height="10" fill="none" stroke="#4a5566" stroke-width="2" />
    <rect x="367" y="125" width="10" height="10" fill="none" stroke="#4a5566" stroke-width="2" />
    <rect x="337" y="107" width="10" height="10" fill="none" stroke="#4a5566" stroke-width="2" />
    <rect x="54" y="124" width="12" height="12" fill="#e4e7eb" />
    <rect x="162" y="64" width="12" height="12" fill="#e4e7eb" />
    <rect x="162" y="184" width="12" height="12" fill="#e4e7eb" />
    <rect x="162" y="124" width="12" height="12" fill="#e4e7eb" />
    <rect x="256" y="34" width="12" height="12" fill="#e4e7eb" />
    <rect x="344" y="144" width="12" height="12" fill="#e4e7eb" />
    <path d="M232 128 L270 125" fill="none" stroke="#7a8494" stroke-width="2" stroke-dasharray="4 4"
      marker-end="url(#gegenpress-arrow-run)" />
    <rect class="gegenpress-p0" x="226" y="122" width="12" height="12" fill="#e4e7eb" />
    <path d="M228 60 L272 108" fill="none" stroke="#7a8494" stroke-width="2" stroke-dasharray="4 4"
      marker-end="url(#gegenpress-arrow-run)" />
    <rect class="gegenpress-p1" x="222" y="54" width="12" height="12" fill="#e4e7eb" />
    <path d="M222 200 L272 142" fill="none" stroke="#7a8494" stroke-width="2" stroke-dasharray="4 4"
      marker-end="url(#gegenpress-arrow-run)" />
    <rect class="gegenpress-p2" x="216" y="194" width="12" height="12" fill="#e4e7eb" />
    <path d="M300 52 L290 108" fill="none" stroke="#7a8494" stroke-width="2" stroke-dasharray="4 4"
      marker-end="url(#gegenpress-arrow-run)" />
    <rect class="gegenpress-p3" x="294" y="46" width="12" height="12" fill="#e4e7eb" />
    <path d="M318 205 L295 145" fill="none" stroke="#7a8494" stroke-width="2" stroke-dasharray="4 4"
      marker-end="url(#gegenpress-arrow-run)" />
    <rect class="gegenpress-p4" x="312" y="199" width="12" height="12" fill="#e4e7eb" />
    <circle class="gegenpress-ball-static" cx="294" cy="132" r="4" fill="#00e8ff" stroke="#05070a" stroke-width="1.5" />
    <circle class="gegenpress-ball-anim" r="4" fill="#00e8ff" stroke="#05070a" stroke-width="1.5">
      <animateMotion dur="1.2s" repeatCount="indefinite" calcMode="linear" path="M294 132 L297 129 L292 134 L294 132"
        keyPoints="0;1" keyTimes="0;1" />
    </circle>
  </svg>
</template>
<style>
.gegenpress-ball-static {
  display: none;
}

@media (prefers-reduced-motion: reduce) {
  .gegenpress-ball-anim {
    display: none;
  }

  .gegenpress-ball-static {
    display: inline;
  }
}

@media (prefers-reduced-motion: no-preference) {
  .gegenpress-zone {
    transform-box: fill-box;
    transform-origin: center;
    animation: gegenpress-zone 3s ease-in-out infinite;
  }

  @keyframes gegenpress-zone {

    0%,
    100% {
      transform: scale(1);
    }

    55% {
      transform: scale(0.72);
    }
  }

  .gegenpress-p0 {
    animation: gegenpress-p0 3s ease-in-out infinite;
  }

  @keyframes gegenpress-p0 {

    0%,
    100% {
      transform: translate(0, 0);
    }

    55% {
      transform: translate(28px, -2px);
    }
  }

  .gegenpress-p1 {
    animation: gegenpress-p1 3s ease-in-out infinite;
  }

  @keyframes gegenpress-p1 {

    0%,
    100% {
      transform: translate(0, 0);
    }

    55% {
      transform: translate(33px, 36px);
    }
  }

  .gegenpress-p2 {
    animation: gegenpress-p2 3s ease-in-out infinite;
  }

  @keyframes gegenpress-p2 {

    0%,
    100% {
      transform: translate(0, 0);
    }

    55% {
      transform: translate(38px, -44px);
    }
  }

  .gegenpress-p3 {
    animation: gegenpress-p3 3s ease-in-out infinite;
  }

  @keyframes gegenpress-p3 {

    0%,
    100% {
      transform: translate(0, 0);
    }

    55% {
      transform: translate(-8px, 42px);
    }
  }

  .gegenpress-p4 {
    animation: gegenpress-p4 3s ease-in-out infinite;
  }

  @keyframes gegenpress-p4 {

    0%,
    100% {
      transform: translate(0, 0);
    }

    55% {
      transform: translate(-17px, -45px);
    }
  }
}
</style>