// Package academy implements the club youth-academy investment model (PRD §23,
// S08-01/A04): configurable investment tiers, facility/scouting/staff levels,
// recurring maintenance overhead, and the seasonal procedural youth intake.
// Intake prospects are generated by pkg/playergen (region-biased), persisted
// through playerpool's shared materialiser, and signed to youth contracts via
// finance.
package academy

import (
	"errors"
	"time"

	"github.com/google/uuid"

	"github.com/touchline/backend/pkg/apiref"
	"github.com/touchline/backend/pkg/playergen"
)

// Event types emitted to world.events by this package.
const (
	EventIntake           = "ACADEMY_INTAKE"
	EventCountryIntake    = "COUNTRY_ACADEMY_INTAKE"
	EventInvestmentChange = "ACADEMY_INVESTMENT_CHANGED"
	EventShutdown         = "ACADEMY_SHUTDOWN"
	EventReopened         = "ACADEMY_REOPENED"
	EventMaintenance      = "ACADEMY_MAINTENANCE"
)

// Sentinel errors surfaced to HTTP handlers.
var (
	ErrClubNotFound   = errors.New("academy: club not found")
	ErrNotOwned       = errors.New("academy: club not managed by actor")
	ErrInvalidTier    = errors.New("academy: invalid investment tier")
	ErrWorldNotActive = errors.New("academy: world not active")
)

// Numerical constants (docs/design/academy-numerics.md). Kept as proposal data:
// a balance pass edits this table, not the logic.
const (
	// DaysPerSeason is the canonical world-season length used to derive the
	// season number from the daily world calendar (matches world/matchday).
	DaysPerSeason = 364

	MinTier = 1
	MaxTier = 5

	// YouthIntakeMinAge / MaxAge span the club-academy intake cohort.
	YouthIntakeMinAge = 15
	YouthIntakeMaxAge = 17

	// ShutdownSentimentPenalty is the immediate supporter hit when a club
	// shuts its academy (emergency cash relief has a boardroom cost).
	ShutdownSentimentPenalty = 15

	// Street intake band (country academy): very young free agents.
	StreetMinCount = 10
	StreetMaxCount = 20
	StreetMinAge   = 13
	StreetMaxAge   = 15
)

// AnnualCostByTier is a club academy's seasonal operating cost. Monthly
// maintenance debits annual_cost/12.
var AnnualCostByTier = map[int]int64{
	1: 250_000,
	2: 600_000,
	3: 1_200_000,
	4: 2_400_000,
	5: 4_800_000,
}

// UpgradeCostByTier is the one-off facilities debit when a club moves INTO
// that tier (charged only on upgrade). Deduped per (club, tier), so bouncing
// back to a tier already paid for never double-charges.
var UpgradeCostByTier = map[int]int64{
	1: 0,
	2: 400_000,
	3: 900_000,
	4: 2_000_000,
	5: 4_500_000,
}

// tierTalentOdds skews prospect talent rarity by investment tier: a tier-5
// academy occasionally finds a wonderkid, a tier-1 one almost never does.
// Each profile sums to 1000.
var tierTalentOdds = map[int]playergen.TalentOdds{
	1: {Journeyman: 980, TopProspect: 18, Wonderkid: 2, Generational: 0},
	2: {Journeyman: 950, TopProspect: 45, Wonderkid: 5, Generational: 0},
	3: {Journeyman: 900, TopProspect: 90, Wonderkid: 9, Generational: 1},
	4: {Journeyman: 830, TopProspect: 150, Wonderkid: 18, Generational: 2},
	5: {Journeyman: 750, TopProspect: 210, Wonderkid: 35, Generational: 5},
}

// TalentOddsForTier returns the rarity profile for an investment tier.
func TalentOddsForTier(tier int) playergen.TalentOdds {
	if odds, ok := tierTalentOdds[clampTier(tier)]; ok {
		return odds
	}
	return playergen.WorldTalentOdds
}

// ProspectCountForTier is the intake cohort size: 3 + tier*2 (5..13).
func ProspectCountForTier(tier int) int {
	return 3 + clampTier(tier)*2
}

// QualityOffsetForTier skews generated prospect attribute baselines:
// tier*3 + reputation/10, capped at ±20.
func QualityOffsetForTier(tier, reputation int) int {
	off := clampTier(tier)*3 + reputation/10
	if off > 20 {
		off = 20
	}
	if off < -20 {
		off = -20
	}
	return off
}

func clampTier(tier int) int {
	if tier < MinTier {
		return MinTier
	}
	if tier > MaxTier {
		return MaxTier
	}
	return tier
}

// AcademyConfig is a club academy's mutable configuration. Zero fields mean
// "leave unchanged" for ConfigureAcademy; IsActive nil preserves the flag.
type AcademyConfig struct {
	InvestmentTier int
	FacilityLevel  int
	ScoutingLevel  int
	StaffQuality   int
	IsActive       *bool
	RegionalReach  []string
}

// Academy is the read model for GET /api/clubs/:id/academy. The club id stays
// internal; the wire carries a nested club ref.
type Academy struct {
	ClubID           uuid.UUID       `json:"-"`
	Club             *apiref.ClubRef `json:"club"`
	WorldID          uuid.UUID       `json:"world_id"`
	IsActive         bool            `json:"is_active"`
	InvestmentTier   int             `json:"investment_tier"`
	FacilityLevel    int             `json:"facility_level"`
	ScoutingLevel    int             `json:"scouting_level"`
	StaffQuality     int             `json:"staff_quality"`
	AnnualCost       int64           `json:"annual_cost"`
	Reputation       int             `json:"reputation"`
	RegionalReach    []string        `json:"regional_reach"`
	LastIntakeSeason int             `json:"last_intake_season"`
	ShutdownAt       *time.Time      `json:"shutdown_at,omitempty"`
	ReopenedAt       *time.Time      `json:"reopened_at,omitempty"`
}

// SeasonForDay derives the canonical season number from an absolute world day
// counter (world launched_at + current_day; DaysPerSeason days per season,
// zero-based season 0).
func SeasonForDay(day int64) int {
	if day < 0 {
		return 0
	}
	return int(day / DaysPerSeason)
}
