<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useTacticsStore } from '~/stores/tactics'
const store = useTacticsStore(); const { value, saving } = storeToRefs(store)
const clubId = ref(''); const style = ref('balanced'); const formation = ref('4-3-3'); const error = ref('')
const styles = [{key:'balanced',label:'Balanced'},{key:'possession',label:'Possession Control'},{key:'gegenpress',label:'Gegenpress'},{key:'low_block',label:'Low-Block / Counter'},{key:'direct',label:'Direct / Long-Ball'}]
async function init() { const {authedFetch}=useAuth(); const r=await authedFetch('/api/clubs'); const clubs=await r.json(); clubId.value=clubs[0]?.id ?? ''; if(!clubId.value) return; await store.load(clubId.value); style.value=value.value?.style ?? style.value; formation.value=value.value?.formation ?? formation.value }
async function save() { if(!clubId.value)return; try { await store.save(clubId.value,style.value,formation.value); error.value='' } catch(e) { error.value=e instanceof Error?e.message:'Could not save tactics.' } }
watch(style, async () => { if (!clubId.value) return; await store.load(clubId.value); const allowed = value.value?.style === style.value ? value.value.allowed_formations : []; if (!allowed.includes(formation.value)) formation.value = allowed[0] ?? formation.value })
onMounted(() => init().catch(() => error.value='Could not load your club.'))
</script>
<template><main class="min-h-screen bg-slate-900 px-6 py-10 text-slate-200"><div class="mx-auto max-w-3xl space-y-6"><h1 class="text-3xl font-bold text-white">Tactics</h1><p class="text-slate-400">Choose one Simple-Mode style. The server freezes it at kick-off.</p><p v-if="error" class="text-red-400">{{ error }}</p><div class="grid gap-3 sm:grid-cols-2"><button v-for="s in styles" :key="s.key" @click="style=s.key" class="rounded border p-4 text-left" :class="style===s.key?'border-indigo-400 bg-indigo-950':'border-slate-700 bg-slate-800'"><strong>{{s.label}}</strong><span class="block text-sm text-slate-400">{{s.key}}</span></button></div><label class="block">Formation<select v-model="formation" class="ml-3 rounded bg-slate-800 p-2"><option v-for="f in (value?.allowed_formations ?? ['4-3-3'])" :key="f">{{f}}</option></select></label><button @click="save" :disabled="saving" class="rounded bg-indigo-600 px-4 py-2 font-medium text-white">{{saving?'Saving…':'Save tactics'}}</button></div></main></template>
