// Package bootstrap produces the material state of a new world (S03-01): an
// AI starter club with its policy-bot manager and a procedurally generated
// first squad, persisted via pkg/playergen under one world_id.
//
// Scope (approved for S03-01): a single starter club per bootstrap; no
// competition structure — league composition/formats stay an open product
// decision (OPD-01) for S04-01. Assignment of the club to a human manager
// happens only through the OPD-16 offer->accept path; this package never
// auto-hires.
//
// Determinism: one seeded *rand.Rand drives the whole operation, and the seed
// is recorded on the WORLD_BOOTSTRAPPED event's random_seed column so the
// output is reproducible (golden-replay source).
package bootstrap

import (
	"context"
	cryptorand "crypto/rand"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/touchline/backend/pkg/eventbus"
	"github.com/touchline/backend/pkg/playergen"
)

// Sentinel errors. Handlers map these to HTTP status codes.
var (
	ErrWorldNotFound        = errors.New("world not found")
	ErrWorldNotProvisioning = errors.New("world must be provisioning to bootstrap")
	ErrAlreadyBootstrapped  = errors.New("world is already bootstrapped")
	ErrRefDataMissing       = errors.New("reference data missing: run cmd/ref-seed before bootstrapping")
	ErrClubNameRequired     = errors.New("club name is required")
)

// SquadSizeDefault is the generated first-squad size (24: 2 GK / 7 DEF / 7 MID
// / 6 FWD / 2 flexible). Data in code, matching the Phase-0 scope.
const SquadSizeDefault = 24

// squadTemplateSlot associates a slot index with the primary positions it may
// accept. GK is rigid; the flexible slots may take any outfield position.
func squadTemplate(size int) [][]string {
	template := [][]string{
		{"GK"}, {"GK"},
		{"CB", "LB", "RB"}, {"CB", "LB", "RB"}, {"CB", "LB", "RB"}, {"CB", "LB", "RB"},
		{"CB", "LB", "RB"}, {"CB", "LB", "RB"}, {"CB", "LB", "RB"},
		{"DM", "CM", "AM", "LM", "RM"}, {"DM", "CM", "AM", "LM", "RM"},
		{"DM", "CM", "AM", "LM", "RM"}, {"DM", "CM", "AM", "LM", "RM"},
		{"DM", "CM", "AM", "LM", "RM"}, {"DM", "CM", "AM", "LM", "RM"}, {"DM", "CM", "AM", "LM", "RM"},
		{"LW", "RW", "ST"}, {"LW", "RW", "ST"}, {"LW", "RW", "ST"},
		{"LW", "RW", "ST"}, {"LW", "RW", "ST"}, {"LW", "RW", "ST"},
	}
	out := make([][]string, 0, size)
	for i := 0; len(out) < size; i++ {
		slot := template[i%len(template)]
		if i >= len(template) {
			slot = []string{"CB", "LB", "RB", "DM", "CM", "AM", "LM", "RM", "LW", "RW", "ST"}
		}
		out = append(out, slot)
	}
	return out
}

// SquadPlayer is one generated, persisted squad member.
type SquadPlayer struct {
	ID              uuid.UUID `json:"id"`
	PersonID        uuid.UUID `json:"person_id"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	DisplayName     string    `json:"display_name"`
	NationalityCode string    `json:"nationality_code"`
	DateOfBirth     time.Time `json:"date_of_birth"`
	Age             int       `json:"age"`
	PrimaryPosition string    `json:"primary_position"`
	SquadNumber     int       `json:"squad_number"`
}

// Result describes the material generated by one bootstrap.
type Result struct {
	WorldID    uuid.UUID     `json:"world_id"`
	ClubID     uuid.UUID     `json:"club_id"`
	ClubName   string        `json:"club_name"`
	ManagerID  uuid.UUID     `json:"manager_id"`
	SquadSize  int           `json:"squad_size"`
	RandomSeed int64         `json:"random_seed"`
	Players    []SquadPlayer `json:"players"`
}

// Publishable mirrors the world/manager event sink. May be nil: the event log
// (world.events) is always written transactionally regardless of the bus.
type Publishable interface {
	Publish(ctx context.Context, event *eventbus.Event) error
}

// Service orchestrates one bootstrap operation.
type Service struct {
	pool *pgxpool.Pool
	bus  Publishable
	rng  *rand.Rand // injected for deterministic tests (production: crypto-seeded)
}

// NewService builds the bootstrap service.
func NewService(pool *pgxpool.Pool, bus Publishable) *Service {
	return &Service{pool: pool, bus: bus}
}

// newServiceWith builds a service with an injected random source, so tests can
// reproduce identical squads for a given seed.
func newServiceWith(pool *pgxpool.Pool, bus Publishable, rng *rand.Rand) *Service {
	return &Service{pool: pool, bus: bus, rng: rng}
}

// BootstrapWorld generates a world's material start state: an AI starter club,
// its policy-bot manager, and a generated squad — all under one world_id.
//
// The world must be 'provisioning' and must not already hold clubs. The whole
// generation is buildable atomically in the DB, and the auditable
// CLUB_CREATED / WORLD_BOOTSTRAPPED events are recorded in the same
// transaction (published to the bus only after commit).
func (s *Service) BootstrapWorld(ctx context.Context, worldID uuid.UUID, clubName, clubShortName string) (*Result, error) {
	if clubName == "" {
		return nil, ErrClubNameRequired
	}
	if clubShortName == "" {
		clubShortName = shortName(clubName)
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin bootstrap tx: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	// Serialize on the world row; a provisioning world can only be bootstrapped once.
	var (
		worldStatus string
		worldRef    time.Time // season reference date for date_of_birth derivation
	)
	err = tx.QueryRow(ctx,
		`SELECT status, COALESCE(launched_at, created_at) FROM world.worlds WHERE id = $1 FOR UPDATE`,
		worldID,
	).Scan(&worldStatus, &worldRef)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrWorldNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("load world: %w", err)
	}
	if worldStatus != "provisioning" {
		return nil, ErrWorldNotProvisioning
	}

	var exists bool
	if err := tx.QueryRow(ctx,
		`SELECT EXISTS (SELECT 1 FROM club.clubs WHERE world_id = $1)`, worldID).Scan(&exists); err != nil {
		return nil, fmt.Errorf("check existing clubs: %w", err)
	}
	if exists {
		return nil, ErrAlreadyBootstrapped
	}

	// Runtime pools come from the reference data the ref-seed binary loaded.
	generator, natPool, err := loadPools(ctx, tx)
	if err != nil {
		return nil, err
	}

	// Seed the rng; record the seed on the bootstrap event for replay.
	seed := s.seed()
	registry := playergen.NewNameRegistry()
	factory := playergen.NewPlayerFactory(generator, natPool, rand.New(rand.NewSource(seed))).WithRegistry(registry)
	squad, err := generateSquad(factory, SquadSizeDefault)
	if err != nil {
		return nil, err
	}

	// 1. The starter club (AI-controlled from the start).
	var clubID uuid.UUID
	if err := tx.QueryRow(ctx, `
		INSERT INTO club.clubs (world_id, name, short_name, country, is_ai_controlled)
		VALUES ($1, $2, $3, 'england', TRUE) RETURNING id`,
		worldID, clubName, clubShortName,
	).Scan(&clubID); err != nil {
		return nil, fmt.Errorf("insert club: %w", err)
	}

	// 2. Its policy-bot manager (offer-origination boundary stays OPD-16).
	var managerID uuid.UUID
	if err := tx.QueryRow(ctx, `
		INSERT INTO manager.managers (world_id, is_policy_bot, status, current_club_id)
		VALUES ($1, TRUE, 'active', $2) RETURNING id`,
		worldID, clubID,
	).Scan(&managerID); err != nil {
		return nil, fmt.Errorf("insert policy-bot manager: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`UPDATE club.clubs SET current_manager_id = $2 WHERE id = $1`, clubID, managerID); err != nil {
		return nil, fmt.Errorf("assign manager: %w", err)
	}

	// 3. People + players.
	ref := daysTruncate(worldRef)
	players := make([]SquadPlayer, 0, len(squad))
	for i, gp := range squad {
		var personID uuid.UUID
		if err := tx.QueryRow(ctx, `
			INSERT INTO person.people
				(world_id, first_name, last_name, display_name, date_of_birth, nationality_code)
			VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
			worldID, gp.FirstName, gp.LastName, gp.DisplayName, dobFor(ref, gp.Age), gp.NationalityCode,
		).Scan(&personID); err != nil {
			return nil, fmt.Errorf("insert person: %w", err)
		}

		var playerID uuid.UUID
		number := i + 1
		if err := tx.QueryRow(ctx, `
			INSERT INTO player.players
				(world_id, person_id, club_id, primary_position, squad_number, status)
			VALUES ($1, $2, $3, $4, $5, 'active') RETURNING id`,
			worldID, personID, clubID, gp.PrimaryPosition, number,
		).Scan(&playerID); err != nil {
			return nil, fmt.Errorf("insert player: %w", err)
		}

		players = append(players, SquadPlayer{
			ID:              playerID,
			PersonID:        personID,
			FirstName:       gp.FirstName,
			LastName:        gp.LastName,
			DisplayName:     gp.DisplayName,
			NationalityCode: gp.NationalityCode,
			DateOfBirth:     dobFor(ref, gp.Age),
			Age:             gp.Age,
			PrimaryPosition: gp.PrimaryPosition,
			SquadNumber:     number,
		})
	}

	// 4. Auditable events (same tx, so the log can never disagree with state).
	seedValue := seed
	actor := "system"
	clubEvent := &eventbus.Event{
		WorldID:   worldID,
		WorldTick: 0,
		EventType: "CLUB_CREATED",
		Payload: mustJSON(map[string]any{
			"club_id":    clubID,
			"club_name":  clubName,
			"manager_id": managerID,
			"squad_size": len(players),
		}),
	}
	bootEvent := &eventbus.Event{
		WorldID:    worldID,
		WorldTick:  0,
		EventType:  "WORLD_BOOTSTRAPPED",
		RandomSeed: &seedValue,
		Payload: mustJSON(map[string]any{
			"club_count":  1,
			"squad_size":  len(players),
			"random_seed": seed,
		}),
	}
	events := []*eventbus.Event{}
	for _, e := range []*eventbus.Event{clubEvent, bootEvent} {
		e.ActorType = &actor
		if err := tx.QueryRow(ctx, `
			INSERT INTO world.events (world_id, world_tick, event_type, actor_type, payload, random_seed)
			VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, occurred_at`,
			e.WorldID, e.WorldTick, e.EventType, actor, e.Payload, e.RandomSeed,
		).Scan(&e.ID, &e.OccurredAt); err != nil {
			return nil, fmt.Errorf("record %s event: %w", e.EventType, err)
		}
		events = append(events, e)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit bootstrap: %w", err)
	}

	// Record-then-publish: the log is authoritative; the bus fans out after
	// commit so a transient publish failure never corrupts generated state.
	if s.bus != nil {
		for _, e := range events {
			if err := s.bus.Publish(ctx, e); err != nil {
				return nil, fmt.Errorf("publish %s event: %w", e.EventType, err)
			}
		}
	}

	return &Result{
		WorldID:    worldID,
		ClubID:     clubID,
		ClubName:   clubName,
		ManagerID:  managerID,
		SquadSize:  len(players),
		RandomSeed: seed,
		Players:    players,
	}, nil
}

// seed returns a fresh crypto-random seed, or the injected one in tests.
func (s *Service) seed() int64 {
	if s.rng != nil {
		return s.rng.Int63()
	}
	var b [8]byte
	if _, err := cryptorand.Read(b[:]); err != nil {
		// crypto/rand never fails in practice; fall back to time so the
		// operation can proceed rather than block on a failure.
		return time.Now().UnixNano()
	}
	return int64(binary.LittleEndian.Uint64(b[:]))
}

// loadPools reads the runtime name/nationality pools from the reference data
// (OPD-13: runtime squad generation reads the DB pools; pkg/playergen stays
// DB-free). Only codes present in BOTH tables participate, so a nationality
// can never be selected without usable names.
func loadPools(ctx context.Context, tx pgx.Tx) (*playergen.PoolGenerator, *playergen.NationalityPool, error) {
	names := map[string][]string{} // code -> first names
	surnames := map[string][]string{}
	rows, err := tx.Query(ctx, `
		SELECT nationality_code, name_type, name
		FROM ref.name_pool
		WHERE name_type IN ('first', 'last')
		ORDER BY nationality_code, name_type, name`)
	if err != nil {
		return nil, nil, fmt.Errorf("query name pool: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var code, kind, name string
		if err := rows.Scan(&code, &kind, &name); err != nil {
			return nil, nil, fmt.Errorf("scan name: %w", err)
		}
		if kind == "first" {
			names[code] = append(names[code], name)
		} else {
			surnames[code] = append(surnames[code], name)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, nil, fmt.Errorf("iterate name pool: %w", err)
	}

	generator := playergen.NewPoolGenerator()
	natPool := playergen.NewNationalityPool()

	nats, err := tx.Query(ctx, `
		SELECT code, name, generation_weight
		FROM ref.nationalities
		WHERE generation_weight > 0
		ORDER BY code`)
	if err != nil {
		return nil, nil, fmt.Errorf("query nationalities: %w", err)
	}
	defer nats.Close()
	for nats.Next() {
		var code, natName string
		var weight float64
		if err := nats.Scan(&code, &natName, &weight); err != nil {
			return nil, nil, fmt.Errorf("scan nationality: %w", err)
		}
		first, okF := names[code]
		last, okL := surnames[code]
		if !okF || !okL {
			continue // no usable name pool → exclude
		}
		if err := generator.AddPool(code, first, last); err != nil {
			continue // empty list → exclude
		}
		natPool.Add(playergen.Nationality{Code: code, Name: natName, Weight: weight})
	}

	if len(natPool.Entries()) == 0 {
		return nil, nil, ErrRefDataMissing
	}
	return generator, natPool, nil
}

// generateSquad builds a squad respecting the position template by rejection
// sampling: a player is accepted when its primary position fits the slot, with
// a bounded retry budget per slot to avoid pathological loops.
func generateSquad(factory *playergen.PlayerFactory, size int) ([]*playergen.GeneratedPlayer, error) {
	template := squadTemplate(size)
	out := make([]*playergen.GeneratedPlayer, 0, size)
	for _, allowed := range template {
		gp, err := generateForPosition(factory, allowed)
		if err != nil {
			return nil, err
		}
		out = append(out, gp)
	}
	return out, nil
}

// generateForPosition draws players until one matches the slot's allowed set.
// Every draw has a positive probability of matching, so this terminates almost
// surely; a bounded "accept anything" fallback would silently degrade the
// position balance (e.g. a rare goalkeeper slot landing on an outfielder).
func generateForPosition(factory *playergen.PlayerFactory, allowed []string) (*playergen.GeneratedPlayer, error) {
	for {
		gp, err := factory.CreatePlayer()
		if err != nil {
			return nil, fmt.Errorf("generate player: %w", err)
		}
		if contains(allowed, gp.PrimaryPosition) {
			return gp, nil
		}
	}
}

func contains(list []string, v string) bool {
	for _, s := range list {
		if s == v {
			return true
		}
	}
	return false
}

// shortName derives a default abbreviation (e.g. "Harbour City FC" -> "Har").
func shortName(name string) string {
	const n = 3
	runes := []rune(name)
	if len(runes) < n {
		return name
	}
	return string(runes[:n])
}

// daysTruncate strips the time component of the world's season reference date.
func daysTruncate(t time.Time) time.Time {
	return time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
}

// dobFor derives the player's date_of_birth from the world reference date.
func dobFor(seasonRef time.Time, age int) time.Time {
	return seasonRef.AddDate(-age, 0, 0)
}

func mustJSON(v map[string]any) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("bootstrap: marshal payload: %v", err))
	}
	return b
}
