// Package bootstrap produces the material state of a new world (S03-01): an
// AI starter club with its policy-bot manager and a first squad drafted from
// the world-level free-agent pool, persisted via pkg/playergen under one
// world_id.
//
// Scope (approved for S03-01): a single starter club per bootstrap; no
// competition structure — league composition/formats stay an open product
// decision (OPD-01) for S04-01. Assignment of the club to a human manager
// happens only through the OPD-16 offer->accept path; this package never
// auto-hires.
//
// Determinism: one seeded *rand.Rand drives the whole operation, and the seed
// is recorded on the WORLD_BOOTSTRAPPED event's random_seed column so the
// output is reproducible (golden-replay source).
package bootstrap

import (
	"context"
	cryptorand "crypto/rand"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	internalboard "github.com/touchline/backend/internal/board"
	"github.com/touchline/backend/internal/finance"
	"github.com/touchline/backend/internal/playerpool"
	"github.com/touchline/backend/pkg/eventbus"
	"github.com/touchline/backend/pkg/playergen"
)

// Sentinel errors. Handlers map these to HTTP status codes.
var (
	ErrWorldNotFound        = errors.New("world not found")
	ErrWorldNotProvisioning = errors.New("world must be provisioning to bootstrap")
	ErrAlreadyBootstrapped  = errors.New("world is already bootstrapped")
	ErrRefDataMissing       = errors.New("reference data missing: run cmd/ref-seed before bootstrapping")
	ErrClubNameRequired     = errors.New("club name is required")
)

// SquadSizeDefault is the drafted first-squad size (24: 2 GK / 7 DEF / 7 MID
// / 6 FWD / 2 flexible). Data in code, matching the Phase-0 scope. The
// position template that guides the draft lives in internal/playerpool.
const SquadSizeDefault = 24

// SquadPlayer is one drafted, persisted squad member.
type SquadPlayer struct {
	ID              uuid.UUID `json:"id"`
	PersonID        uuid.UUID `json:"person_id"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	DisplayName     string    `json:"display_name"`
	NationalityCode string    `json:"nationality_code"`
	DateOfBirth     time.Time `json:"date_of_birth"`
	Age             int       `json:"age"`
	PrimaryPosition string    `json:"primary_position"`
	SquadNumber     int       `json:"squad_number"`
}

// Result describes the material generated by one bootstrap.
type Result struct {
	WorldID    uuid.UUID     `json:"world_id"`
	ClubID     uuid.UUID     `json:"club_id"`
	ClubName   string        `json:"club_name"`
	ManagerID  uuid.UUID     `json:"manager_id"`
	SquadSize  int           `json:"squad_size"`
	RandomSeed int64         `json:"random_seed"`
	Players    []SquadPlayer `json:"players"`
}

// GeneratedClub is the per-club material produced by GenerateAIClub. S04-01
// league seeding calls GenerateAIClub once per additional AI team inside its
// own transaction, so every league entry gets the same squad machinery the
// starter club gets.
type GeneratedClub struct {
	ClubID    uuid.UUID     `json:"club_id"`
	ClubName  string        `json:"club_name"`
	ManagerID uuid.UUID     `json:"manager_id"`
	SquadSize int           `json:"squad_size"`
	Players   []SquadPlayer `json:"players"`
}

// Publishable mirrors the world/manager event sink. May be nil: the event log
// (world.events) is always written transactionally regardless of the bus. Only
// the tx-scoped outbox method is required (OPD-23).
type Publishable interface {
	eventbus.Publisher
}

// Service orchestrates one bootstrap operation.
type Service struct {
	pool *pgxpool.Pool
	bus  Publishable
	rng  *rand.Rand // injected for deterministic tests (production: crypto-seeded)
}

// NewService builds the bootstrap service.
func NewService(pool *pgxpool.Pool, bus Publishable) *Service {
	return &Service{pool: pool, bus: bus}
}

// newServiceWith builds a service with an injected random source, so tests can
// reproduce identical squads for a given seed.
func newServiceWith(pool *pgxpool.Pool, bus Publishable, rng *rand.Rand) *Service {
	return &Service{pool: pool, bus: bus, rng: rng}
}

// BootstrapWorld generates a world's material start state: an AI starter club,
// its policy-bot manager, and a generated squad — all under one world_id.
//
// The world must be 'provisioning' and must not already hold clubs. The whole
// generation is buildable atomically in the DB, and the auditable
// CLUB_CREATED / WORLD_BOOTSTRAPPED events are recorded in the same
// transaction (published to the bus only after commit).
func (s *Service) BootstrapWorld(ctx context.Context, worldID uuid.UUID, clubName, clubShortName string) (*Result, error) {
	if clubName == "" {
		return nil, ErrClubNameRequired
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin bootstrap tx: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	// Serialize on the world row; a provisioning world can only be bootstrapped once.
	var worldStatus string
	var worldRef time.Time // season reference date for date_of_birth derivation
	err = tx.QueryRow(ctx,
		`SELECT status, COALESCE(launched_at, created_at) FROM world.worlds WHERE id = $1 FOR UPDATE`,
		worldID,
	).Scan(&worldStatus, &worldRef)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrWorldNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("load world: %w", err)
	}
	if worldStatus != "provisioning" {
		return nil, ErrWorldNotProvisioning
	}

	var exists bool
	if err := tx.QueryRow(ctx,
		`SELECT EXISTS (SELECT 1 FROM club.clubs WHERE world_id = $1)`, worldID).Scan(&exists); err != nil {
		return nil, fmt.Errorf("check existing clubs: %w", err)
	}
	if exists {
		return nil, ErrAlreadyBootstrapped
	}

	// Runtime pools come from the reference data the ref-seed binary loaded.
	generator, natPool, err := LoadPools(ctx, tx)
	if err != nil {
		return nil, err
	}

	// Seed the rng; record the seed on the bootstrap event for replay.
	seed := s.seed()
	registry := playergen.NewNameRegistry()
	factory := playergen.NewPlayerFactory(generator, natPool, rand.New(rand.NewSource(seed))).WithRegistry(registry)

	// World-level free-agent pool (country_id NULL — the country isn't created
	// until league seeding). The starter club drafts from it below; the pool
	// is then replenished back to target so a signing market exists from day 0.
	ref := daysTruncate(worldRef)
	if _, err := playerpool.SeedPool(ctx, tx, s.bus, worldID, nil, playerpool.PoolTargetSize, factory, ref); err != nil {
		return nil, fmt.Errorf("seed world pool: %w", err)
	}

	// The starter club drafts its 24 from the world-level pool, then the pool
	// is topped back up for future activity.
	club, err := GenerateAIClub(ctx, s.bus, tx, worldID, clubName, clubShortName, "england", nil)
	if err != nil {
		return nil, err
	}
	if err := playerpool.ReplenishPool(ctx, tx, s.bus, worldID, nil, playerpool.PoolTargetSize, factory, ref); err != nil {
		return nil, fmt.Errorf("replenish world pool: %w", err)
	}

	// The boot event names the seed that produced the whole world's first squad.
	seedValue := seed
	actor := "system"
	bootEvent := &eventbus.Event{
		WorldID:    worldID,
		WorldTick:  0,
		EventType:  "WORLD_BOOTSTRAPPED",
		RandomSeed: &seedValue,
		Payload: mustJSON(map[string]any{
			"club_count":  1,
			"squad_size":  club.SquadSize,
			"random_seed": seed,
		}),
	}
	bootEvent.ActorType = &actor
	// Record + enqueue in the same tx (the transactional outbox, OPD-23): the
	// boot is never committed without its dispatch job.
	if err := recordEvent(ctx, s.bus, tx, bootEvent); err != nil {
		return nil, fmt.Errorf("record WORLD_BOOTSTRAPPED event: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit bootstrap: %w", err)
	}

	return &Result{
		WorldID:    worldID,
		ClubID:     club.ClubID,
		ClubName:   club.ClubName,
		ManagerID:  club.ManagerID,
		SquadSize:  club.SquadSize,
		RandomSeed: seed,
		Players:    club.Players,
	}, nil
}

// GenerateAIClub persists one AI-controlled club, its policy-bot manager, and a
// squad drafted from the free-agent pool inside the caller's transaction, and
// records the auditable CLUB_CREATED event in the same tx (the log can never
// disagree with state).
//
// It is the smallest reusable unit of world materialization: BootstrapWorld
// uses it for the starter club, and S04-01 league seeding calls it once per
// additional AI team, always inside the caller's own transaction. The caller
// is responsible for ensuring the pool is seeded/replenished before calling.
// poolCountryID may be nil for the world-level bootstrap pool.
func GenerateAIClub(ctx context.Context, pub eventbus.Publisher, tx pgx.Tx, worldID uuid.UUID, clubName, clubShortName, country string, poolCountryID *uuid.UUID) (*GeneratedClub, error) {
	if clubName == "" {
		return nil, ErrClubNameRequired
	}
	if clubShortName == "" {
		clubShortName = shortName(clubName)
	}

	var worldRef time.Time // season reference date for date_of_birth derivation
	err := tx.QueryRow(ctx,
		`SELECT COALESCE(launched_at, created_at) FROM world.worlds WHERE id = $1`,
		worldID,
	).Scan(&worldRef)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrWorldNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("load world: %w", err)
	}

	// 1. The AI-controlled club.
	var clubID uuid.UUID
	if err := tx.QueryRow(ctx, `
		INSERT INTO club.clubs (world_id, name, short_name, country, is_ai_controlled)
		VALUES ($1, $2, $3, $4, TRUE) RETURNING id`,
		worldID, clubName, clubShortName, country,
	).Scan(&clubID); err != nil {
		return nil, fmt.Errorf("insert club: %w", err)
	}

	// 1b. Deterministic board profile: club DNA, the owning board's persona,
	// and the supporter group's baseline (S06-02 reads these on the weekly
	// review). Seeded from the club's identity so the profile never changes.
	profile, persona, _ := profileFor(clubName, clubID)
	if err := seedBoardProfile(ctx, tx, clubID, profile, persona); err != nil {
		return nil, err
	}

	// 2. Its policy-bot manager (offer-origination boundary stays OPD-16).
	var managerID uuid.UUID
	if err := tx.QueryRow(ctx, `
		INSERT INTO manager.managers (world_id, is_policy_bot, status, current_club_id)
		VALUES ($1, TRUE, 'active', $2) RETURNING id`,
		worldID, clubID,
	).Scan(&managerID); err != nil {
		return nil, fmt.Errorf("insert policy-bot manager: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`UPDATE club.clubs SET current_manager_id = $2 WHERE id = $1`, clubID, managerID); err != nil {
		return nil, fmt.Errorf("assign manager: %w", err)
	}

	// 3. Draft the squad from the free-agent pool.
	ref := daysTruncate(worldRef)
	draft, err := playerpool.DraftSquad(ctx, tx, pub, worldID, clubID, poolCountryID, ref, SquadSizeDefault)
	if err != nil {
		return nil, fmt.Errorf("draft squad: %w", err)
	}

	// 4. Financial genesis in the same tx: the ledger account and opening
	// capital, the season's transfer + wage budgets, and a starter contract
	// with wage commitment for the full squad (S05-02).
	if err := finance.BootstrapClub(ctx, tx, worldID, clubID, ref, draft.Seeds); err != nil {
		return nil, fmt.Errorf("seed club finances: %w", err)
	}

	// 5. Build the SquadPlayer slice from the draft for the return value.
	players := make([]SquadPlayer, 0, len(draft.Players))
	for _, d := range draft.Players {
		players = append(players, SquadPlayer{
			ID:              d.PlayerID,
			PersonID:        d.PersonID,
			FirstName:       d.FirstName,
			LastName:        d.LastName,
			DisplayName:     d.DisplayName,
			NationalityCode: d.NationalityCode,
			DateOfBirth:     d.DateOfBirth,
			Age:             d.Age,
			PrimaryPosition: d.PrimaryPosition,
			SquadNumber:     d.SquadNumber,
		})
	}

	// 6. The auditable creation event (same tx).
	actor := "system"
	clubEvent := &eventbus.Event{
		WorldID:   worldID,
		EventType: "CLUB_CREATED",
		Payload: mustJSON(map[string]any{
			"club_id":        clubID,
			"club_name":      clubName,
			"manager_id":     managerID,
			"squad_size":     len(players),
			"contract_count": len(draft.Seeds),
		}),
	}
	clubEvent.ActorType = &actor
	if err := recordEvent(ctx, pub, tx, clubEvent); err != nil {
		return nil, fmt.Errorf("record CLUB_CREATED event: %w", err)
	}

	return &GeneratedClub{
		ClubID:    clubID,
		ClubName:  clubName,
		ManagerID: managerID,
		SquadSize: len(players),
		Players:   players,
	}, nil
}

// seedBoardProfile writes the deterministic club DNA, board and supporter
// group rows in one tx. Any column set later is fine to leave at its seeded
// value; the review engine re-reads whatever is stored.
func seedBoardProfile(ctx context.Context, tx pgx.Tx, clubID uuid.UUID, p clubProfile, persona internalboard.Persona) error {
	if _, err := tx.Exec(ctx, `
		INSERT INTO club.club_dna (
			club_id, competitive_ambition, financial_philosophy, recruitment_philosophy,
			academy_importance, patience, managerial_control, star_power_preference,
			wage_tolerance, selling_philosophy, tactical_identity, cultural_identity, archetype)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
		clubID, p.ambition, p.financialPhilosophy, p.recruitmentPhilosophy,
		p.academyImportance, p.patience, p.managerialControl, p.starPowerPreference,
		p.wageTolerance, p.sellingPhilosophy, p.tacticalIdentity, p.culturalIdentity, p.archetype); err != nil {
		return fmt.Errorf("insert club dna: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO club.boards (club_id, personality_type) VALUES ($1, $2)`,
		clubID, persona); err != nil {
		return fmt.Errorf("insert club board: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO club.supporter_groups (
			club_id, patience, ambition, loyalty, identity, rivalry_intensity_base,
			financial_sensitivity, current_sentiment)
		VALUES ($1, $2, $3, $4, $5, 0, $6, 50)`,
		clubID, p.patience, p.ambition, p.supporterLoyalty, p.supporterIdentity,
		p.supporterFinancialSensitivity); err != nil {
		return fmt.Errorf("insert supporter group: %w", err)
	}
	return nil
}

// recordEvent appends one world.events row inside the caller's transaction and,
// when a publisher is wired, enqueues its dispatch job in the same tx (OPD-23).
func recordEvent(ctx context.Context, pub eventbus.Publisher, tx pgx.Tx, e *eventbus.Event) error {
	actor := "system"
	e.ActorType = &actor
	return eventbus.WriteTx(ctx, pub, tx, e)
}

// seed returns a fresh crypto-random seed, or the injected one in tests.
func (s *Service) seed() int64 {
	if s.rng != nil {
		return s.rng.Int63()
	}
	var b [8]byte
	if _, err := cryptorand.Read(b[:]); err != nil {
		// crypto/rand never fails in practice; fall back to time so the
		// operation can proceed rather than block on a failure.
		return time.Now().UnixNano()
	}
	return int64(binary.LittleEndian.Uint64(b[:]))
}

// LoadPools reads the runtime name/nationality pools from the reference data
// (OPD-13: runtime squad generation reads the DB pools; pkg/playergen stays
// DB-free). Only codes present in BOTH tables participate, so a nationality
// can never be selected without usable names. It runs against a transaction so
// S04-01 league seeding can generate squads inside its own atomic operation.
func LoadPools(ctx context.Context, tx pgx.Tx) (*playergen.PoolGenerator, *playergen.NationalityPool, error) {
	names := map[string][]string{} // code -> first names
	surnames := map[string][]string{}
	rows, err := tx.Query(ctx, `
		SELECT nationality_code, name_type, name
		FROM ref.name_pool
		WHERE name_type IN ('first', 'last')
		ORDER BY nationality_code, name_type, name`)
	if err != nil {
		return nil, nil, fmt.Errorf("query name pool: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var code, kind, name string
		if err := rows.Scan(&code, &kind, &name); err != nil {
			return nil, nil, fmt.Errorf("scan name: %w", err)
		}
		if kind == "first" {
			names[code] = append(names[code], name)
		} else {
			surnames[code] = append(surnames[code], name)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, nil, fmt.Errorf("iterate name pool: %w", err)
	}

	generator := playergen.NewPoolGenerator()
	natPool := playergen.NewNationalityPool()

	nats, err := tx.Query(ctx, `
		SELECT code, name, generation_weight
		FROM ref.nationalities
		WHERE generation_weight > 0
		ORDER BY code`)
	if err != nil {
		return nil, nil, fmt.Errorf("query nationalities: %w", err)
	}
	defer nats.Close()
	for nats.Next() {
		var code, natName string
		var weight float64
		if err := nats.Scan(&code, &natName, &weight); err != nil {
			return nil, nil, fmt.Errorf("scan nationality: %w", err)
		}
		first, okF := names[code]
		last, okL := surnames[code]
		if !okF || !okL {
			continue // no usable name pool → exclude
		}
		if err := generator.AddPool(code, first, last); err != nil {
			continue // empty list → exclude
		}
		natPool.Add(playergen.Nationality{Code: code, Name: natName, Weight: weight})
	}

	if len(natPool.Entries()) == 0 {
		return nil, nil, ErrRefDataMissing
	}
	return generator, natPool, nil
}

// shortName derives a default abbreviation (e.g. "Harbour City FC" -> "Har").
func shortName(name string) string {
	const n = 3
	runes := []rune(name)
	if len(runes) < n {
		return name
	}
	return string(runes[:n])
}

// daysTruncate strips the time component of the world's season reference date,
// using the UTC calendar day so the anchor is timezone-independent and matches
// the matchday world-day counter (see matchday.worldDate).
func daysTruncate(t time.Time) time.Time {
	y, m, d := t.UTC().Date()
	return time.Date(y, m, d, 0, 0, 0, 0, time.UTC)
}

func mustJSON(v map[string]any) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("bootstrap: marshal payload: %v", err))
	}
	return b
}
