apiVersion: v1
kind: Service
metadata:
  name: {{ include "touchline-worker.fullname" . }}
  labels:
    app: {{ include "touchline-worker.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "touchline-worker.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http