replicaCount: 1

image:
  repository: ghcr.io/touchline/scheduler
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  SCHEDULER_PORT: "8081"
  ENV: production

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi